### PR TITLE
 Added Proxy support

### PR DESCRIPTION
**Pull request by tschechniker**

### CODE REVIEW

**Comment by essiembre** [comment]
Thanks for your contribution!  I've accepted it, and I added the ability (optional) to encrypt the proxy password. I made a new 1.4.0-SNAPSHOT release.  Please confirm it works for you.

**Comment by essiembre** [comment]
Closing since merged in the latest snapshot.  Please open a new ticket if you run into issues.

**Comment by tschechniker** [comment]
Hi @essiembre,

sorry for the late reply. I tested the 1.4.0-SNAPSHOT and it's working. Would it be posibile to release the 1.4.0 version?

**Comment by essiembre** [comment]
Cloudsearch Committer 1.4.0 was just released.

**Pull request closed without merging**
